import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/shared/ui/components/header";
import { Footer } from "@/shared/ui/components/footer";
import { ScrollProgress } from "@/shared/ui/components/scroll-progress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-br flex flex-col from-gray-900 via-purple-900 to-black text-white">
          <Header />
          <ScrollProgress />
          <main className="container mx-auto py-8 px-4 md:px-8 flex-1">
            {children}
          </main>
          <Footer />
          {modal}
        </div>
      </body>
    </html>
  );
}
